version: '3'

services:
  php:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    command: php -S 0.0.0.0:8000 -t /app
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root